In [2]:
from numpy import array
import numpy as np

In [8]:
arr = array([7, 52, 36, 9, 18, 741], np.int8())
arr

array([  7,  52,  36,   9,  18, -27], dtype=int8)

In [9]:
print(type(arr))

<class 'numpy.ndarray'>


In [47]:
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 72]
               ])
nd_arr.dtype

dtype('int32')

In [24]:
arr[2] = 3000
arr[3] = 9.15
arr[1] = '52'
arr

array([  7,  52, -72,   9,  18, -27], dtype=int8)

In [26]:
arr = np.float32(arr)
arr

array([  7.,  52., -72.,   9.,  18., -27.], dtype=float32)

In [27]:
arr = np.array([12321, -1234, 3435, -214, 100], np.uint8)
arr

array([ 33,  46, 107,  42, 100], dtype=uint8)

In [29]:
arr_test = np.array([345234, 876362.12, 0, -1000, 99999999])
arr_test.dtype 

dtype('float64')

In [32]:
arr.ndim
nd_arr.ndim

2

In [34]:
arr.size
nd_arr.size

9

In [36]:
arr.shape
nd_arr.shape

(3, 3)

In [51]:
arr.itemsize
nd_arr = np.int16(nd_arr)
nd_arr.itemsize

2

In [57]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [3]:
zeros_3d = np.zeros((5, 4, 3), dtype=np.float32)
zeros_3d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [68]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [69]:
print(np.arange(5), np.arange(4, 5.1, 0.1, dtype=np.float16), sep='\n')

[0 1 2 3 4]
[4.    4.1   4.203 4.305 4.406 4.508 4.61  4.71  4.812 4.914 5.016]


In [86]:
arr = np.linspace(1, 2, 10, endpoint=True, retstep=True, dtype=np.float16)
arr

(array([1.   , 1.111, 1.223, 1.333, 1.444, 1.556, 1.667, 1.777, 1.889,
        2.   ], dtype=float16),
 0.1111111111111111)

In [95]:
arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True, dtype=np.float16)
print(step)

0.1
