In [14]:
import numpy as np

In [17]:
arr=np.arange(0, 58, 3)
arr.shape = (4, 5)
arr

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42],
       [45, 48, 51, 54, 57]])

In [34]:
new_arr = arr.reshape((5, 4))
new_arr

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33],
       [36, 39, 42, 45],
       [48, 51, 54, 57]])

In [38]:
arr_transp = new_arr.transpose()
arr_transp

array([[ 0, 12, 24, 36, 48],
       [ 3, 15, 27, 39, 51],
       [ 6, 18, 30, 42, 54],
       [ 9, 21, 33, 45, 57]])

In [55]:
arr = np.linspace(1, 6, 12)
arr

array([1.        , 1.45454545, 1.90909091, 2.36363636, 2.81818182,
       3.27272727, 3.72727273, 4.18181818, 4.63636364, 5.09090909,
       5.54545455, 6.        ])

In [59]:
print(arr[2])
print(arr[1:4])
print(arr[::-1])
print(arr[-1])

1.9090909090909092
[1.45454545 1.90909091 2.36363636]
[6.         5.54545455 5.09090909 4.63636364 4.18181818 3.72727273
 3.27272727 2.81818182 2.36363636 1.90909091 1.45454545 1.        ]
6.0


In [61]:
nd_array = np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [68]:
print(nd_array[1][2])
print(nd_array[2, 0])
print(nd_array[:2, 2:])
nd_array[:, 1:3]

3.0
4.0
[[1.  1.5]
 [3.  3.5]]


array([[0.5, 1. ],
       [2.5, 3. ],
       [4.5, 5. ]])

In [69]:
data = np.array([4, 9, -4, 3])
roots = np.sqrt(data)
roots

C:\Users\qwert\AppData\Local\Temp\ipykernel_17764\3612371969.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [70]:
print(type(None))
print(type(np.nan))

<class 'NoneType'>
<class 'float'>


In [71]:
print(None == None)
print(np.nan == np.nan)
print(None is None)
print(np.nan is np.nan)
print(np.nan is None)

True
False
True
True
False


In [72]:
sum(roots)

nan

In [77]:
roots[np.isnan(roots)] = 0
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [76]:
np.isnan(np.nan)


True

In [ ]:
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

elem_5_3 = mystery[4, 2]
last = mystery[-1, -1]
line_4 = mystery[3]
col_2 = mystery[:, -2]
part = mystery[1:4, 2:5] 
rev = mystery[::-1, -1] 
trans = mystery.transpose()  

In [ ]:
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)

nans_index = np.isnan(mystery)

n_nan = sum(nans_index)

mystery_new = mystery
mystery_new[np.isnan(mystery_new)] = 0

mystery_int = np.int32(mystery)

array = np.sort(mystery)

table = array.reshape((5, 3), order='F')

col = table[:, 1]