In [1]:
import numpy as np
np.random.rand()

0.2968598785665999

In [40]:
np.random.rand() * 100

17.606998521352637

In [48]:
print(np.random.rand(5))
np.random.rand(3, 4)

[0.72624661 0.52712108 0.69917368 0.95414681 0.03891345]


array([[0.90096769, 0.16384417, 0.57819276, 0.85953415],
       [0.11742687, 0.17122488, 0.76024089, 0.09295087],
       [0.70666767, 0.23680665, 0.92950744, 0.59040042]])

In [ ]:
np.random.rand(2, 2, 2, 2, 2, 2)

In [52]:
shape = (3, 4)
np.random.rand(*shape)

array([[0.56292728, 0.10334063, 0.71528701, 0.28020831],
       [0.77246058, 0.92987781, 0.28357534, 0.54021824],
       [0.48783559, 0.9686593 , 0.83862845, 0.76240966]])

In [54]:
# Принимаем для формы кортеж без распаковки

shape = (3, 4)
np.random.sample(shape)

array([[0.13652177, 0.71752079, 0.0039189 , 0.58768766],
       [0.48303225, 0.7907364 , 0.28057289, 0.96026528],
       [0.7798875 , 0.57456372, 0.70424261, 0.05498208]])

In [62]:
# Генерация чисел в диапозоне (стандартно от 0 до 1)

print(np.random.uniform())
np.random.uniform(-30, 50, size=(3,4))

0.835263220358622


array([[ 46.28980933, -16.60484285,  12.82697097,  47.50689759],
       [  1.74772894,   8.99350537,  36.23222702,  29.4623517 ],
       [-17.60186041,  -7.54778778,   3.1646714 , -28.40190192]])

In [2]:
# Генерация целых чисел

np.random.randint(1, 7, size=(4, 4, 4))

array([[[6, 6, 3, 6],
        [3, 3, 5, 4],
        [1, 2, 2, 4],
        [1, 6, 3, 6]],

       [[5, 3, 5, 1],
        [4, 2, 4, 5],
        [5, 5, 3, 5],
        [4, 4, 1, 4]],

       [[2, 4, 6, 6],
        [6, 4, 6, 5],
        [4, 4, 5, 6],
        [6, 5, 1, 4]],

       [[2, 5, 3, 1],
        [5, 5, 5, 2],
        [4, 1, 5, 2],
        [3, 4, 6, 3]]])

In [5]:
# Перемешивание чисел в массиве

arr = np.arange(11)
np.random.shuffle(arr)
arr

array([ 7,  4,  6,  3,  1,  9,  0,  2,  5, 10,  8])

In [70]:
#  Получаем новый перемешанный массив, а исходный оставить без изменений

playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print('Initial: ', playlist, '\n', 'New: ', shuffled)

Initial:  ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple'] 
 New:  ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']


In [71]:
np.random.permutation(11)

array([ 1,  6,  5,  0,  2,  7,  9, 10,  3,  4,  8])

In [9]:
# Чтобы получить случайный набор объектов из массива, используется функция random.choice

np.random.choice(arr, size=(2, 3), replace=False)
np.random.choice(10, size=(3, 4), replace=True)

array([[2, 1, 8, 5],
       [9, 9, 5, 6],
       [8, 7, 5, 5]])

In [108]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']

print(np.random.choice(workers, size=3, replace=False))

['Ivan' 'John' 'Nikita']


In [171]:
np.random.seed(1)
print(np.random.randint(23, size=(2, 5)))
print()
np.random.seed(1)
print(np.random.randint(23, size=(2, 5)))
print()
print(np.random.randint(23, size=(2, 5)))

[[ 5 11 12  8  9]
 [11  5 15  0 16]]

[[ 5 11 12  8  9]
 [11  5 15  0 16]]

[[ 1 12  7 13  6]
 [18 20  5 18 20]]
